openapi: 3.1.1

info:
  title: Example API

  version: 1.0.0

  x-logo:
    url: "/images/pinch-logo.svg"
    altText: "Pinch Framework"
    backgroundColor: "#263238"

servers:
  - url: "http://localhost:8888"
    description: Development
  - url: "https://staging.example.com"
    description: Staging
  - url: "https://production.example.com"
    description: Production

security:
  - token: []

paths: {}

components:
  securitySchemes:
    token:
      type: http
      scheme: bearer
      bearerFormat: PASETO
