name: Code Quality Checks

on:
  push:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Code Quality Checks
        run: |
          cp .env.dist .env;
          sed -i "s/^GITHUB_TOKEN=.*/GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}/" ".env";
          sed -i "s%^PINCH_APP_KEY=.*%PINCH_APP_KEY=$(head -c 32 /dev/urandom | base64)%" ".env";
          make -j && make ci;
